### ISSUE TITLE
Allow custom compose filename and/or regex list

### ISSUE THREAD

**Issue by Abashinos** [IamTheFij/docker-pre-commit#15]
Current regex that is used to lookup compose files (`(docker-)?compose.y[a]{0,1}ml$`) is both restrictive (requires custom part of the name to prefix the static part) and fixed.
This naming system prevents effective grouping of multiple compose files, forcing users to employ the `<purpose>.docker-compose.yml` naming instead of `docker-compose.<purpose>.yml`.

I'd suggest allowing users to supply their own regex list as a pre-commit hook argument, e.g.
```yaml
- repo: https://github.com/IamTheFij/docker-pre-commit
   rev: v2.1.1
   hooks:
     - id: docker-compose-check
       args: ["--files", "(docker-)?compose(\.\w+)*\.y[a]{0,1}ml$", "envs/docker-compose.yml"]
```

P.S. Current regex lacks a slash before the dot, so it might match any symbol and admit file names like `docker-composeyyml`
